packages:
  - cli
  - cli/template
  - cli/template/apps/expo
  - cli/template/apps/nextjs
  - cli/template/packages/api
  - cli/template/packages/auth
  - cli/template/packages/db
  - cli/template/packages/config/*
